# Generated by Django 3.2.6 on 2021-08-07 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='uploads/products')),
                ('product_category_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.productcategory')),
            ],
        ),
    ]
